spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "farah.boughit@gmail.com"
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8087

project:
  poster: posters/

base:
  url: "http://localhost:8087"
